### ISSUE TITLE
Docker tags versioning for `lite`

### ISSUE THREAD

**Issue by esbite** [hackmdio/docker-hackmd#11]
We are using the lite version of the docker image, but you are only versioning the master ones. It would be nice if we could lock down our hackmd to `0.5.1-lite` too.

Could you tag the lite images with version too on your docker hub?

**Comment by esbite** [comment]
Maybe you could also rename the `lite` tag to `alpine`? That is what most others use 😃 
You can have a look here how e.g. nodejs tags their images: https://hub.docker.com/_/node/

Your tags could be:
- `0.5.1`, `0.5`, `0`, `latest`
- `0.5.1-alpine`, `0.5-alpine`, `0-alpine`, `alpine`

**Comment by jackycute** [comment]
Hey @SISheogorath 
What do you think?

**Comment by SISheogorath** [comment]
To build it like this we have to define our own build environment.

We can use Travis-CI to build and test the Dockerfile and build and push it to Docker-Hub or use Docker-Cloud hooks for Builds on Docker-Hub: https://docs.docker.com/docker-cloud/builds/advanced/#custom-build-phase-hooks

Renaming the branch is not a problem. Same applies to the CI setup. But what I'm worried about is the case how the `latest` image is currently built.

The current `latest` is super unstable because it always keeps track of the `HEAD` of the https://gihub.com/hackmdio/hackmd master branch.

It's also very difficult right now to keep the `lite` and the `master` branch in sync. I checked today the slim branch and it's nearly completely out of sync with the master. So I would suggest to reunion the master and the slim branch first and move the Dockerfiles into subdirectories which refer to their base image.

A good example how to organize that can be found here: https://github.com/docker-library/ghost/pull/55

In the case of our repository, this says we should move `hackmd/` to `debian/` and add `alpine/` for the new slim builds. Once that's done, we can think about building the images like the official images do.

**Comment by SISheogorath** [comment]
Was fixed with #14 waiting for HackMD 1.0.0-CE coming out.
