### ISSUE TITLE
How to update 1.0.1->1.1.0 properly?

### ISSUE THREAD

**Issue by Himura2la** [hackmdio/docker-hackmd#53]
I did the following:

- Backed up my `docker-compose.yml`
- `git checkout master -f && git pull`
- Restored my changes in `docker-compose.yml`
- Stopped the existing containers
- `docker-compose pull && docker-compose up`

It created two new containers, and the database container contained an empty database.

I continued:
- Started my past database container
- Backed up the data with `docker exec dockerhackmd_database_1 pg_dump hackmd -U hackmd  > backup.sql`
- Started the new database container
- `cat backup.sql | docker exec -i $(docker-compose ps -q database) psql -U hackmd`

I got many errors:
```
SET
SET
SET
SET
SET
SET
SET
SET
CREATE EXTENSION
COMMENT
SET
ALTER TYPE
SET
ERROR:  type "enum_Notes_permission" already exists
SET
ALTER TABLE
ALTER TABLE
ERROR:  relation "Authors" already exists
ERROR:  relation "Authors_id_seq" already exists
ALTER SEQUENCE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ERROR:  relation "Notes" already exists
ERROR:  relation "Revisions" already exists
ERROR:  relation "SequelizeMeta" already exists
ERROR:  relation "Sessions" already exists
ERROR:  relation "Temp" already exists
ERROR:  relation "Temps" already exists
ERROR:  relation "Users" already exists
ALTER TABLE
ALTER TABLE
COPY 23
 setval
--------
     24
(1 row)

COPY 43
COPY 530
ERROR:  duplicate key value violates unique constraint "SequelizeMeta_pkey"
DETAIL:  Key (name)=(20150504155329-create-users.js) already exists.
CONTEXT:  COPY SequelizeMeta, line 1
COPY 33
COPY 0
COPY 0
ERROR:  multiple primary keys for table "Authors" are not allowed
COPY 2
ERROR:  multiple primary keys for table "Notes" are not allowed
ERROR:  multiple primary keys for table "Revisions" are not allowed
ERROR:  multiple primary keys for table "SequelizeMeta" are not allowed
ERROR:  multiple primary keys for table "Sessions" are not allowed
ERROR:  multiple primary keys for table "Temp" are not allowed
ERROR:  multiple primary keys for table "Temps" are not allowed
ERROR:  multiple primary keys for table "Users" are not allowed
ERROR:  relation "Users_profileid_key" already exists
ERROR:  relation "authors_note_id_user_id" already exists
ERROR:  relation "notes_alias" already exists
ERROR:  relation "notes_shortid" already exists
```

After this, I started the `app` container, and the UI constantly shows me this:

![image](https://user-images.githubusercontent.com/7802808/41664125-a849c122-74ad-11e8-9907-8630b6fae76f.png)

It re-opens after refresh and goes away only on cross.

What am I doing wrong?

For some reason I have my past database image without a tag:

```
PS > docker image ls
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
postgres                   9.6-alpine          6583932564f8        11 days ago         39.3MB
hackmdio/hackmd            1.1.0-ce            8c8b29274bdd        4 weeks ago         1.19GB
hackmdio/hackmd            1.0.1-ce            05334bbff0b7        3 months ago        1.17GB
postgres                   <none>              613fcd71a3c8        4 months ago        37.9MB
docker4w/nsenter-dockerd   latest              cae870735e91        7 months ago        187kB
```

By the way, how to clean the database data used by a docker image? I thought it is stored within an image, but somehow the data persists after `docker image rm` and new `docker-compose pull`. I had many problems with it when deleted the `hackmd` database in attempts to avoid errors when restoring a backup...

**Comment by SISheogorath** [comment]
There are two ways:

1. Either do a git pull and pull down all changes and merge them with your local ones. If you want to avoid the need to backup your docker-compose file and restore your changes afterwards, use a `production.yml` to overwrite your configs like described in this document:
https://docs.docker.com/compose/production/

2. You can simply change the version number in the compose file and see if there were any other changes in the recent time so that our dockerfile differs from yours.

---

Now, lets come to the database question. The data of the database are stored in a database volume. Which is specified here:

https://github.com/hackmdio/docker-hackmd/blob/37819b5371fd66b0414e885ead972006cf33d33b/docker-compose.yml#L14-L15

And here:

https://github.com/hackmdio/docker-hackmd/blob/37819b5371fd66b0414e885ead972006cf33d33b/docker-compose.yml#L78-L80

This volume is created by docker-compose on the first startup and should be when using `docker volume ls`.

To delete them, you can either do `docker-compose down` and delete them afterwards by using `docker volume rm` or simply use `docker-compose down -v` which will stop all your running containers and remove the volumes. But keep in mind your data will be gone in this case, so we actually don't recommend it.

After all, even when you removed the volume and you restart the stack and **then** restore your data using the sql file, you end up in conflicts, because when the database is empty the docker images runs the database migrations that creates the needed tables to run HackMD. So if you want to restore you data, do the following:

```console
docker-compose exec database pg_dump hackmd -U hackmd > backup.sql
docker-compose down -v
docker-compose up -d database
cat backup.sql | docker-compose exec database psql -U hackmd
docker-compose up -d
```

That's it :)

---

I hope all questions got answered :)

**Comment by Himura2la** [comment]
Thanks for the comprehensive answer even on non-hackmd-related questions. I wish I had more time with docker, it seems pretty cool. Looks like the names were fixed since the commit I used to raise HackMD and now I have an empty duplicates of everything when trying to update:

```
PS > docker volume ls
DRIVER              VOLUME NAME
local               docker-hackmd_database
local               docker-hackmd_hackmd_uploads
local               dockerhackmd_database
local               dockerhackmd_hackmd_uploads
```

It should be OK now when you have shown me how to properly migrate the data into another container.

**Comment by Himura2la** [comment]
But when I finished the update and run the app on the port used by the previous version, I faced this annoying dialog again

![](https://user-images.githubusercontent.com/7802808/41664125-a849c122-74ad-11e8-9907-8630b6fae76f.png)

Ctrl+F5 helps, but It should be written there!

**Comment by Himura2la** [comment]
I found a problem with your instructions. We've lost all Unicode in the new version (( seems like it's trquired to specify the encoding flags

**Comment by Himura2la** [comment]
I did not have a chance to yet, but I guess specifying the encoding on both ends is not a good idea

**Comment by SISheogorath** [comment]
`pg_dump` by default uses the encoding of the database, so the question is now, where things get lost so we know…:

* …is it the database encoding?
* …the shell encoding in the database container?
* …your shell encoding?
* …the encoding that has to be specified for psql?

**Comment by Himura2la** [comment]
Well, I think I can't pick up the right encoding for the backup file. It looks like UTF-16, because I see spaces after every symbol when opening it ad UTF-8. And none of the two encodings render the correct Cyrillic symbols
